version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: u2024
      POSTGRES_PASSWORD: 8a7ecta86&5!4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
