
GET http://localhost:5127/api/product

###
GET http://localhost:5127/api/product/1

###

POST http://localhost:5127/api/product
content-type: application/json

{
    "name": "Test t-shirt",
    "price": "71.33",
    "settings": "{\"fabrics\":[{\"name\":\"silk\",\"colors\":[{\"name\":\"white\",\"images\":[\"base64-1\",\"base64-2\"]},{\"name\":\"black\",\"images\":[\"base64-1\",\"base64-2\"]}]}]}"
}

###

DELETE http://localhost:5127/api/product/3
content-type: application/json

###

PUT http://localhost:5127/api/product/1
content-type: application/json

{
    "name": "Test 777",
    "price": "1.33"
}

